title: Nitish's Blog
description: "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
author:
  name: Nitishkumar Akalwadi
  email: 'nitish_akalwadi@yahoo.co.incididunt'
  url: http://nitishakalwadi.tk
  logo:
  gravatar: 
  description: ""
blog:
  route: ''
metadata:
    description: ''
taxonomies: [category,tag,month]

menu:
  # - url: error
  #   text: Error Page
  # - url: yo man
  #   text: yo man page

# Copyright
# copyright: Created By <a href="http://www.soratemplates.com/" rel="dofollow" target="_blank" title="Blogger Templates">Sora Templates</a> and <a href="http://mybloggerthemes.com/" rel="dofollow" target="_blank" title="Blogger Templates">My Blogger Themes</a> , Ported By <a href="http://www.getgrav.org" rel="dofollow" target="_blank" title="Grav">Grav Team</a>
